### ISSUE TITLE
 Resource punkt_tab not found.

### ISSUE THREAD

**Issue by syedasad-kiwi** [Storia-AI/sage#40]
Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/Users/kiwitech/nltk_data'
    - '/Users/kiwitech/Documents/SageAI/venv/nltk_data'
    - '/Users/kiwitech/Documents/SageAI/venv/share/nltk_data'
    - '/Users/kiwitech/Documents/SageAI/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

Have downloaded this, but still the same error is there.

**Comment by iuliaturc** [comment]
@syedasad-kiwi To help me debug, could you please provide some information about your setup:
- Are you using `pipx` or `pip` + `venv`?
- What version of `nltk` is installed in your environment?
- What Python version are you using?

I'm seeing that on a fresh environment it's automatically downloading these dependencies for me, and I'm trying to figure out what the discrepancy between our setups is.

**Comment by mihail911** [comment]
Can you check #42 @syedasad-kiwi?

**Comment by asadnhasan** [comment]
Are you using pipx or pip + venv? - pip + venv
What version of nltk is installed in your environment? - 3.9.1
What Python version are you using? - 3.12.5

**Comment by mihail911** [comment]
can you try this PR @asadnhasan @syedasad-kiwi ? are you still running into this issue?
