### ISSUE TITLE
How to access Private Repos | I have PAT for the REPO

### ISSUE THREAD

**Issue by syedasad-kiwi** [Storia-AI/sage#41]
I want to use this on my Private Repo. Is the functionality still there ?

If Yes, how to do this via PAT?

**Comment by iuliaturc** [comment]
Hi @syedasad-kiwi, you can work with a private repository by setting a `GITHUB_TOKEN` environment variable, which we pick up [here](https://github.com/Storia-AI/sage/blob/21a0427b61652cd7b5feaa4674c5b72467fa4c51/sage/data_manager.py#L60).

Let me know if you encounter any issues!
