### ISSUE TITLE
[FEATURE REQUEST] Expand to other vector stores beyond Pinecone

### ISSUE THREAD

**Issue by iuliaturc** [Storia-AI/sage#65]
**Is your feature request related to a problem? Please describe.**
Solely supporting Pinecone is reportedly a deal breaker for some users, see for instance [this comment](https://news.ycombinator.com/item?id=41564857).

**Describe the solution you'd like**
We should expand to other providers, at least top 5 supported by LangChain (Weaviate, Milvus, FAISS, Chroma, Qdrant). We should also allow mixing local LLMs with remote vector stores (currently, local LLMs only go with local Marqo vector store).

**Comment by LuciAkirami** [comment]
Can I work on this @iuliaturc ? Hey @aazam-gh maybe we each can take a separate vector database and integrate them

**Comment by iuliaturc** [comment]
Apologies for the late response, I need to adjust my notifications :)

I'll assign this to @aazam-gh on a first-come-first-serve basis. Splitting the work based on vector stores is not a bad idea, but it might be prone to conflicts.

@LuciAkirami would you like to take https://github.com/Storia-AI/sage/issues/47 instead? I marked it as "difficulty 2" but really I think it's "difficulty 1" but more fun :D

**Comment by LuciAkirami** [comment]
Thanks for the other task @iuliaturc, but I do not think, I may be able to do that. I have replied to this issue as I have previously worked on integrating a vector db to mem0(previously known as Embedchain)

**Comment by iuliaturc** [comment]
@aazam-gh Just checking in -- are you still working on this issue?

**Comment by LuciAkirami** [comment]
Is this issue still available to work on?

**Comment by iuliaturc** [comment]
@LuciAkirami I'll assign it to you due to inactivity from the previous assignee.
