### ISSUE TITLE
Add unit tests for vector_store.py

### ISSUE THREAD

**Issue by iuliaturc** [Storia-AI/sage#79]
Unit tests should go under the [tests/](https://github.com/Storia-AI/sage/tree/main/tests) folder.

The interactions with Pinecone and Marqo will have to be mocked out.

**Comment by aarya-16** [comment]
Hello @iuliaturc since I'm currently working on implementing reciprocal rank fusion in this file, I'd like to try this as well, so that I can add the tests once the changes have been made.

**Comment by iuliaturc** [comment]
Makes sense, I'll assign it to you then :)

**Comment by adityabharadwaj198** [comment]
I went ahead and added tests. I've opened a [pull request](https://github.com/Storia-AI/sage/pull/98), @iuliaturc. Would appreciate your review
