### ISSUE TITLE
[BUG] Our current CI/CD for code formatting is broken

### ISSUE THREAD

**Issue by iuliaturc** [Storia-AI/sage#80]
**Describe the bug**
Currently, the automation we have for code formatting [here](https://github.com/Storia-AI/sage/blob/main/.github/workflows/ci.yml) is broken in most cases.

My intention was to have an automation that runs `isort` and `black --line-length=120` on every PR and adds a commit with formatted code. However:
- It actually fails most of the time
- It can't run on public PRs, needs the approval of the maintainers

**To Reproduce**
You can look at the history of actions, and see that it fails for various reasons (see [example](https://github.com/Storia-AI/sage/actions/runs/11294124069/job/31417940942)).

**Expected behavior**
- The less error-prone thing would be to have it run the formatting, but not attempt to make an actual commit.
- After removing the automated commit, we should make it easy for developers to run these formatting tools themselves by providing e.g. .vscode defaults.
- You can take inspiration from [this GPT response](https://chatgpt.com/share/67095f6c-8aec-8013-af4c-2d7441ef3786) and feel free to take liberties if you think there's a better practice here.

**Comment by laksh-krishna-sharma** [comment]
Hi @iuliaturc , may i work on this issue.

**Comment by Firdous2307** [comment]
@iuliaturc Can I work on this issue?
