### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by pvishalkeerthan** [Storia-AI/sage#85]
I would like to add a footer, include a star symbol for the GitHub stars on the homepage, and improve the UI

<img width="657" alt="image" src="https://github.com/user-attachments/assets/2110f64f-3128-49b5-8ea7-5dac1c7b4322">

@iuliaturc Would like to work on this

**Comment by pvishalkeerthan** [comment]
Thanks for the clarification! Just to confirm, will this be included in the Dev Fest open source contributions? I’d love to contribute to the README in that context

**Comment by iuliaturc** [comment]
If the contribution to the README is meaningful, I'm happy to tag your pull request with "hacktoberfest-accepted".
