### ISSUE TITLE
can sage release a stable version repo

### ISSUE THREAD

**Issue by CoderYiFei** [Storia-AI/sage#89]
can sage release a stable version repo

**Comment by iuliaturc** [comment]
Hi @CoderYiFei! Are you referring to pushing a stable version to pypi?

**Comment by CoderYiFei** [comment]
yes , it s better to show at here
/
<img width="487" alt="截屏2024-10-22 13 20 53" src="https://github.com/user-attachments/assets/fda3c02c-8d46-43c7-a892-e2592cc48941">
below the "Release"

**Comment by iuliaturc** [comment]
We now have a stable release `storia-sage v0.1.0`

**Comment by CoderYiFei** [comment]
> We now have a stable release `storia-sage v0.1.0`

very nice.. thank you...
